spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/roomescape?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qwer1234!
    hikari:
      maximum-pool-size: 15
      minimum-idle: 10
      connection-timeout: 5000

security:
  jwt:
    token:
      secret-key: YzbMlPH7Bt4HXEjizwC2RxFtcWGLxSgZKDt9XOZm0IAyUv3yD5rth1sf7fw9NRFWgIe3aOeYgTEaMBYOd7iE4jIvS1f5SEaMJDUrI
      expire-length: 3600000
